import Head from "next/head";
import { AiOutlineSortAscending } from "react-icons/ai";
import Dropdown from "../src/components/Helper/Dropdown";
import Banner from "../src/components/Home/Banner";
import ProductGrid from "../src/components/product/ProductGrid";
import { DOMAIN } from "../src/utils/const";
import withLayout from "./layout.manager";

export const DEMO_PRODUCT = {
  title: "Headphone gamer Version",
  rating: { value: 3.9, count: 10 },
  desc: "Easily transfer your Skype for Business and Lync pc calls to your smartphone using â€œJabra Intelligent call transfer (JICT).",
  images: ["https://www.bhphotovideo.com/images/images500x500/philips_tak4206bl_00_k4206_kids_wireless_on_ear_1689932.jpg",
    "https://m.media-amazon.com/images/I/51WPZWeeafS._AC_SX569_.jpg",
  ],
};

export default function Home({ data = [], error = "" }) {
  data = [];
  // if (error)
  //   return (
  //     <h1 className="font-mono text-4xl font-bold text-indigo-800">{error}</h1>
  //   );
  return (
    <>
      <Head>
        <title>Dot Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Banner />
        {/* PRODUCT GIRDS */}
        <section className="py-16">
          <div className="container flex flex-row items-center">
            <div className="flex flex-grow flex-row flex-nowrap gap-2 overflow-auto py-1">
              <select name="name">
                <option value="">HELLo</option>
              </select>
              <select name="name">
                <option value="">HELLo</option>
              </select>
              <select name="name">
                <option value="">HELLo</option>
              </select>
              <select name="name">
                <option value="">HELLo</option>
              </select>
            </div>
            <Dropdown
              buttonClass="px-3 pr-3 py-2"
              from="right-0"
              title={
                <>
                  <AiOutlineSortAscending className="inline-block" /> Sort
                </>
              }
              menuClass=""
              menu={["A-Z", "Z-A", "Low Price", "High Price"]}
            />
          </div>
          <ProductGrid
            className="py-5"
            products={[DEMO_PRODUCT, DEMO_PRODUCT, DEMO_PRODUCT, DEMO_PRODUCT, DEMO_PRODUCT, DEMO_PRODUCT]}
            error={error}
          />
        </section>
      </>
    </>
  );
}

export async function getServerSideProps() {
  let URL = `${DOMAIN}/api/v1/products`;
  let props = { data: [], error: "", url: URL };
  try {
    let data = await (await fetch(URL)).json();
    props.data = data;
    props.error = null;
  } catch (error) {
    props.data = [];
    console.error(error);
    props.error = error.message;
  }
  return {
    props: props, // will be passed to the page component as props
  };
}

Home.getLayout = withLayout(); //DEFAULT LAYOUT
