import Head from "next/head";
import Banner from "../components/Home/Banner";
import ProductGrid from "../components/product/ProductGrid";
import { BASE_API_ROUTE } from "../const";
import withLayout from "./layout.manager";

const demo = {
  title: "Headphone gamer Version",
  rating: { value: 3.9, count: 10 },
  desc: "Easily transfer your Skype for Business and Lync pc calls to your smartphone using â€œJabra Intelligent call transfer (JICT).",
  images: [
    "https://www.bhphotovideo.com/images/images500x500/philips_tak4206bl_00_k4206_kids_wireless_on_ear_1689932.jpg",
    "https://m.media-amazon.com/images/I/51WPZWeeafS._AC_SX569_.jpg",
  ],
};

export default function Home({ data = [], error = "" }) {
  data = [];
  if (error)
    return (
      <h1 className="text-4xl font-bold font-mono text-indigo-800">{error}</h1>
    );
  return (
    <>
      <Head>
        <title>Dot Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Banner />
        {/* PRODUCT GIRDS */}
        <section className="py-16">
          <div className="container flex flex-row items-center">
            <div className=" flex flex-row overflow-auto flex-nowrap gap-3 flex-grow py-1">
              <select name="model">
                <option value="">Model</option>
                <option value="model-1">Model 1</option>
              </select>
              <select name="brand">
                <option value="">Brand</option>
                <option value="model-1">Model 1</option>
              </select>
              <select name="color">
                <option value="">Color</option>
                <option value="model-1">Model 1</option>
              </select>
              <select name="color">
                <option value="">Material</option>
                <option value="model-1">Model 1</option>
              </select>
            </div>
            <select name="sort">
              <option value="">Sort</option>
              <option value="">Sort</option>
            </select>
          </div>
          <ProductGrid className="py-5" products={[demo, demo,demo,demo,demo,demo]} error={error} />
        </section>
      </>
    </>
  );
}

export async function getServerSideProps() {
  let URL = `${BASE_API_ROUTE}/api/v1/products`;
  let props = { data: [], error: "", url: URL };
  try {
    let data = await (await fetch(URL)).json();
    props.data = data;
    props.error = null;
  } catch (error) {
    props.data = [];
    console.error(error);
    props.error = error.message;
  }
  return {
    props: props, // will be passed to the page component as props
  };
}

Home.getLayout = withLayout(); //DEFAULT LAYOUT
